#!/usr/bin/env bash

sudo apt-get update 
sudo apt-get install unzip wget -y  
wget https://releases.hashicorp.com/vault/1.8.0+ent/vault_1.8.0+ent_linux_amd64.zip
unzip vault_1.8.0+ent_linux_amd64.zip
sudo mv vault /usr/local/bin  
mkdir -p /home/ubuntu/vault-demo/vault/data
